# Generated by Django 5.2.9 on 2025-12-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='bio',
            field=models.TextField(blank=True, db_column='bio', db_comment='自己紹介文', max_length=500, null=True, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='career_history',
            field=models.TextField(blank=True, db_column='career_history', db_comment='職務経歴や学歴など', null=True, verbose_name='経歴'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='github_url',
            field=models.URLField(blank=True, db_column='github_url', db_comment='GitHubプロフィールリンク', max_length=255, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='icon',
            field=models.TextField(blank=True, db_column='icon', max_length=100, null=True, verbose_name='ユーザーアイコン'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='is_email_notification_enabled',
            field=models.BooleanField(db_column='is_email_notification_enabled', db_comment='すべてのメール通知をONにするか', db_default=True, default=True, verbose_name='メール通知一括ON/OFF'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='is_public',
            field=models.BooleanField(db_column='is_public', db_comment='プロフィールを一般公開するかどうか', db_default=True, default=True, verbose_name='プロフィール公開フラグ'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='location',
            field=models.CharField(blank=True, db_column='location', db_comment='所在地（例：東京都、日本）', max_length=100, null=True, verbose_name='所在地'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='notify_comment',
            field=models.BooleanField(db_column='notify_comment', db_comment='コメントや返信が来た時のメール通知', db_default=True, default=True, verbose_name='通知:コメント/返信'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='notify_follow',
            field=models.BooleanField(db_column='notify_follow', db_comment='誰かにフォローされた時のメール通知', db_default=True, default=True, verbose_name='通知:フォロー'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='notify_like',
            field=models.BooleanField(db_column='notify_like', db_comment='作品に「いいね」がついた時のメール通知', db_default=True, default=True, verbose_name='通知:作品いいね'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='portfolio_blog_url',
            field=models.URLField(blank=True, db_column='portfolio_blog_url', db_comment='個人ポートフォリオまたはブログのリンク', max_length=255, null=True, verbose_name='ポートフォリオ/ブログ URL'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='skill_tags_raw',
            field=models.CharField(blank=True, db_column='skill_tags_raw', db_comment='得意な技術タグ（カンマ区切りなどの生データ）', max_length=500, null=True, verbose_name='得意な技術タグ（RAW）'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='x_url',
            field=models.URLField(blank=True, db_column='x_url', db_comment='X (旧Twitter) プロフィールリンク', max_length=255, null=True, verbose_name='X (旧Twitter) URL'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='bio',
            field=models.TextField(blank=True, db_column='bio', db_comment='自己紹介文', max_length=500, null=True, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='career_history',
            field=models.TextField(blank=True, db_column='career_history', db_comment='職務経歴や学歴など', null=True, verbose_name='経歴'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='github_url',
            field=models.URLField(blank=True, db_column='github_url', db_comment='GitHubプロフィールリンク', max_length=255, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='icon',
            field=models.ImageField(blank=True, db_column='icon', null=True, upload_to='user_icons/', verbose_name='ユーザーアイコン'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='is_email_notification_enabled',
            field=models.BooleanField(db_column='is_email_notification_enabled', db_comment='すべてのメール通知をONにするか', db_default=True, default=True, verbose_name='メール通知一括ON/OFF'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='is_public',
            field=models.BooleanField(db_column='is_public', db_comment='プロフィールを一般公開するかどうか', db_default=True, default=True, verbose_name='プロフィール公開フラグ'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='location',
            field=models.CharField(blank=True, db_column='location', db_comment='所在地（例：東京都、日本）', max_length=100, null=True, verbose_name='所在地'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='notify_comment',
            field=models.BooleanField(db_column='notify_comment', db_comment='コメントや返信が来た時のメール通知', db_default=True, default=True, verbose_name='通知:コメント/返信'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='notify_follow',
            field=models.BooleanField(db_column='notify_follow', db_comment='誰かにフォローされた時のメール通知', db_default=True, default=True, verbose_name='通知:フォロー'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='notify_like',
            field=models.BooleanField(db_column='notify_like', db_comment='作品に「いいね」がついた時のメール通知', db_default=True, default=True, verbose_name='通知:作品いいね'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='portfolio_blog_url',
            field=models.URLField(blank=True, db_column='portfolio_blog_url', db_comment='個人ポートフォリオまたはブログのリンク', max_length=255, null=True, verbose_name='ポートフォリオ/ブログ URL'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='skill_tags_raw',
            field=models.CharField(blank=True, db_column='skill_tags_raw', db_comment='得意な技術タグ（カンマ区切りなどの生データ）', max_length=500, null=True, verbose_name='得意な技術タグ（RAW）'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='x_url',
            field=models.URLField(blank=True, db_column='x_url', db_comment='X (旧Twitter) プロフィールリンク', max_length=255, null=True, verbose_name='X (旧Twitter) URL'),
        ),
    ]
