# Generated by Django 5.2.9 on 2025-12-07 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_historicalm_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalm_userprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='historicalm_userprofile',
            name='is_email_notification_enabled',
        ),
        migrations.RemoveField(
            model_name='historicalm_userprofile',
            name='notify_comment',
        ),
        migrations.RemoveField(
            model_name='historicalm_userprofile',
            name='notify_follow',
        ),
        migrations.RemoveField(
            model_name='historicalm_userprofile',
            name='notify_like',
        ),
        migrations.RemoveField(
            model_name='historicalm_userprofile',
            name='portfolio_blog_url',
        ),
        migrations.RemoveField(
            model_name='historicalm_userprofile',
            name='x_url',
        ),
        migrations.RemoveField(
            model_name='m_userprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='m_userprofile',
            name='is_email_notification_enabled',
        ),
        migrations.RemoveField(
            model_name='m_userprofile',
            name='notify_comment',
        ),
        migrations.RemoveField(
            model_name='m_userprofile',
            name='notify_follow',
        ),
        migrations.RemoveField(
            model_name='m_userprofile',
            name='notify_like',
        ),
        migrations.RemoveField(
            model_name='m_userprofile',
            name='portfolio_blog_url',
        ),
        migrations.RemoveField(
            model_name='m_userprofile',
            name='x_url',
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='github_link',
            field=models.URLField(blank=True, db_column='github_link', db_comment='GitHubプロフィールリンク', max_length=255, null=True, verbose_name='GitHubリンク'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='is_email_notify_enabled',
            field=models.BooleanField(db_column='is_email_notify_enabled', db_comment='メール通知一括設定フラグ', db_default=True, default=True, verbose_name='メール通知一括設定フラグ'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='is_notify_comment',
            field=models.BooleanField(db_column='is_notify_comment', db_comment='通知:コメントや返信が来た時のメール設定フラグ', db_default=True, default=True, verbose_name='通知:コメント設定フラグ'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='is_notify_follow',
            field=models.BooleanField(db_column='is_notify_follow', db_comment='通知:誰かにフォローされた時のメール設定フラグ', db_default=True, default=True, verbose_name='通知:フォロー設定フラグ'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='is_notify_like',
            field=models.BooleanField(db_column='is_notify_like', db_comment='通知:作品に「いいね」がついた時のメール設定フラグ', db_default=True, default=True, verbose_name='通知:いいね設定フラグ'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='portfolio_blog_link',
            field=models.URLField(blank=True, db_column='portfolio_blog_link', db_comment='ポートフォリオまたはブログのリンク', max_length=255, null=True, verbose_name='ポートフォリオ/ブログリンク'),
        ),
        migrations.AddField(
            model_name='historicalm_userprofile',
            name='x_link',
            field=models.URLField(blank=True, db_column='x_link', db_comment='X (旧Twitter) プロフィールリンク', max_length=255, null=True, verbose_name='X (旧Twitter) リンク'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='github_link',
            field=models.URLField(blank=True, db_column='github_link', db_comment='GitHubプロフィールリンク', max_length=255, null=True, verbose_name='GitHubリンク'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='is_email_notify_enabled',
            field=models.BooleanField(db_column='is_email_notify_enabled', db_comment='メール通知一括設定フラグ', db_default=True, default=True, verbose_name='メール通知一括設定フラグ'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='is_notify_comment',
            field=models.BooleanField(db_column='is_notify_comment', db_comment='通知:コメントや返信が来た時のメール設定フラグ', db_default=True, default=True, verbose_name='通知:コメント設定フラグ'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='is_notify_follow',
            field=models.BooleanField(db_column='is_notify_follow', db_comment='通知:誰かにフォローされた時のメール設定フラグ', db_default=True, default=True, verbose_name='通知:フォロー設定フラグ'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='is_notify_like',
            field=models.BooleanField(db_column='is_notify_like', db_comment='通知:作品に「いいね」がついた時のメール設定フラグ', db_default=True, default=True, verbose_name='通知:いいね設定フラグ'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='portfolio_blog_link',
            field=models.URLField(blank=True, db_column='portfolio_blog_link', db_comment='ポートフォリオまたはブログのリンク', max_length=255, null=True, verbose_name='ポートフォリオ/ブログリンク'),
        ),
        migrations.AddField(
            model_name='m_userprofile',
            name='x_link',
            field=models.URLField(blank=True, db_column='x_link', db_comment='X (旧Twitter) プロフィールリンク', max_length=255, null=True, verbose_name='X (旧Twitter) リンク'),
        ),
        migrations.AlterField(
            model_name='historicalm_user',
            name='created_at',
            field=models.DateTimeField(blank=True, db_column='created_at', db_comment='作成日時', editable=False, null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='historicalm_user',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_comment='作成を行ったユーザー', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='historicalm_user',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_column='updated_at', db_comment='更新日時', editable=False, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='historicalm_user',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_comment='更新を行ったユーザー', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='historicalm_userprofile',
            name='bio',
            field=models.TextField(blank=True, db_column='bio', db_comment='自己紹介文', max_length=500, null=True, verbose_name='自己紹介文'),
        ),
        migrations.AlterField(
            model_name='historicalm_userprofile',
            name='career_history',
            field=models.TextField(blank=True, db_column='career_history', db_comment='経歴（職務経歴や学歴など）', null=True, verbose_name='経歴'),
        ),
        migrations.AlterField(
            model_name='historicalm_userprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, db_column='created_at', db_comment='作成日時', editable=False, null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='historicalm_userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_comment='作成を行ったユーザー', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='historicalm_userprofile',
            name='icon',
            field=models.TextField(blank=True, db_column='icon', db_comment='ユーザーアイコン', max_length=512, null=True, verbose_name='ユーザーアイコン'),
        ),
        migrations.AlterField(
            model_name='historicalm_userprofile',
            name='is_public',
            field=models.BooleanField(db_column='is_public', db_comment='プロフィール公開フラグ', db_default=True, default=True, verbose_name='プロフィール公開フラグ'),
        ),
        migrations.AlterField(
            model_name='historicalm_userprofile',
            name='skill_tags_raw',
            field=models.CharField(blank=True, db_column='skill_tags_raw', db_comment='技術タグ（カンマ区切りなどの生データ）', max_length=500, null=True, verbose_name='技術タグ（RAW）'),
        ),
        migrations.AlterField(
            model_name='historicalm_userprofile',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_column='updated_at', db_comment='更新日時', editable=False, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='historicalm_userprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_comment='更新を行ったユーザー', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='historicalt_usertoken',
            name='created_at',
            field=models.DateTimeField(blank=True, db_column='created_at', db_comment='作成日時', editable=False, null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='historicalt_usertoken',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_comment='作成を行ったユーザー', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='historicalt_usertoken',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_column='updated_at', db_comment='更新日時', editable=False, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='historicalt_usertoken',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_comment='更新を行ったユーザー', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='m_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='m_user',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_comment='作成を行ったユーザー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='m_user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='m_user',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_comment='更新を行ったユーザー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='m_userprofile',
            name='bio',
            field=models.TextField(blank=True, db_column='bio', db_comment='自己紹介文', max_length=500, null=True, verbose_name='自己紹介文'),
        ),
        migrations.AlterField(
            model_name='m_userprofile',
            name='career_history',
            field=models.TextField(blank=True, db_column='career_history', db_comment='経歴（職務経歴や学歴など）', null=True, verbose_name='経歴'),
        ),
        migrations.AlterField(
            model_name='m_userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='m_userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_comment='作成を行ったユーザー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='m_userprofile',
            name='icon',
            field=models.ImageField(blank=True, db_column='icon', db_comment='ユーザーアイコン', max_length=512, null=True, upload_to='user_icons/', verbose_name='ユーザーアイコン'),
        ),
        migrations.AlterField(
            model_name='m_userprofile',
            name='is_public',
            field=models.BooleanField(db_column='is_public', db_comment='プロフィール公開フラグ', db_default=True, default=True, verbose_name='プロフィール公開フラグ'),
        ),
        migrations.AlterField(
            model_name='m_userprofile',
            name='skill_tags_raw',
            field=models.CharField(blank=True, db_column='skill_tags_raw', db_comment='技術タグ（カンマ区切りなどの生データ）', max_length=500, null=True, verbose_name='技術タグ（RAW）'),
        ),
        migrations.AlterField(
            model_name='m_userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='m_userprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_comment='更新を行ったユーザー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='t_loginhisory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='t_loginhisory',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_comment='作成を行ったユーザー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='t_loginhisory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='t_loginhisory',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_comment='更新を行ったユーザー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='t_usertoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='t_usertoken',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', db_comment='作成を行ったユーザー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='t_usertoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='t_usertoken',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_comment='更新を行ったユーザー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
    ]
