# Generated by Django 5.2.9 on 2025-12-08 16:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_historicalm_userprofile_theme_m_userprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalM_UserSettings',
            fields=[
                ('is_email_notify_enabled', models.BooleanField(db_column='is_email_notify_enabled', db_comment='メール通知一括設定フラグ', db_default=True, default=True, verbose_name='メール通知一括設定フラグ')),
                ('is_notify_like', models.BooleanField(db_column='is_notify_like', db_comment='通知:作品に「いいね」がついた時のメール設定フラグ', db_default=True, default=True, verbose_name='通知:いいね設定フラグ')),
                ('is_notify_comment', models.BooleanField(db_column='is_notify_comment', db_comment='通知:コメントや返信が来た時のメール設定フラグ', db_default=True, default=True, verbose_name='通知:コメント設定フラグ')),
                ('is_notify_follow', models.BooleanField(db_column='is_notify_follow', db_comment='通知:誰かにフォローされた時のメール設定フラグ', db_default=True, default=True, verbose_name='通知:フォロー設定フラグ')),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', db_comment='作成日時', editable=False, null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', db_comment='更新日時', editable=False, null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_comment='作成を行ったユーザー', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('m_user', models.ForeignKey(blank=True, db_column='m_user_id', db_comment='ユーザマスタ', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_comment='更新を行ったユーザー', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'historical ユーザー設定マスタ',
                'verbose_name_plural': 'historical ユーザー設定マスタ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='M_UserSettings',
            fields=[
                ('m_user', models.OneToOneField(db_column='m_user_id', db_comment='ユーザマスタ', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_setting', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ')),
                ('is_email_notify_enabled', models.BooleanField(db_column='is_email_notify_enabled', db_comment='メール通知一括設定フラグ', db_default=True, default=True, verbose_name='メール通知一括設定フラグ')),
                ('is_notify_like', models.BooleanField(db_column='is_notify_like', db_comment='通知:作品に「いいね」がついた時のメール設定フラグ', db_default=True, default=True, verbose_name='通知:いいね設定フラグ')),
                ('is_notify_comment', models.BooleanField(db_column='is_notify_comment', db_comment='通知:コメントや返信が来た時のメール設定フラグ', db_default=True, default=True, verbose_name='通知:コメント設定フラグ')),
                ('is_notify_follow', models.BooleanField(db_column='is_notify_follow', db_comment='通知:誰かにフォローされた時のメール設定フラグ', db_default=True, default=True, verbose_name='通知:フォロー設定フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', db_comment='作成を行ったユーザー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', db_comment='更新を行ったユーザー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'ユーザー設定マスタ',
                'verbose_name_plural': 'ユーザー設定マスタ',
                'db_table': 'm_user_settings',
                'db_table_comment': 'ユーザー設定マスタ',
            },
        ),
    ]
