# Generated by Django 5.2.9 on 2025-12-08 16:32

from django.db import migrations


def migrate_notification_settings(apps, schema_editor):
    """
    M_UserProfileからM_UserSettingsへ通知設定をコピーする
    """
    M_UserProfile = apps.get_model('account', 'M_UserProfile')
    M_UserSettings = apps.get_model('account', 'M_UserSettings')
    
    # 全てのユーザープロフィールを取得
    profiles = M_UserProfile.objects.filter(deleted_at__isnull=True)
    
    # M_UserSettingsレコードを作成
    settings_to_create = []
    for profile in profiles:
        settings_to_create.append(
            M_UserSettings(
                m_user_id=profile.m_user_id,
                is_email_notify_enabled=profile.is_email_notify_enabled,
                is_notify_like=profile.is_notify_like,
                is_notify_comment=profile.is_notify_comment,
                is_notify_follow=profile.is_notify_follow,
            )
        )
    
    # 一括作成
    M_UserSettings.objects.bulk_create(settings_to_create, ignore_conflicts=True)


def reverse_migration(apps, schema_editor):
    """
    ロールバック時の処理（M_UserSettingsを削除）
    """
    M_UserSettings = apps.get_model('account', 'M_UserSettings')
    M_UserSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_add_user_settings_model'),
    ]

    operations = [
        migrations.RunPython(migrate_notification_settings, reverse_migration),
    ]
