# Generated by Django 5.2.9 on 2025-12-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_migrate_notification_settings_to_user_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalm_userprofile',
            name='is_email_notify_enabled',
        ),
        migrations.RemoveField(
            model_name='historicalm_userprofile',
            name='is_notify_comment',
        ),
        migrations.RemoveField(
            model_name='historicalm_userprofile',
            name='is_notify_follow',
        ),
        migrations.RemoveField(
            model_name='historicalm_userprofile',
            name='is_notify_like',
        ),
        migrations.RemoveField(
            model_name='m_userprofile',
            name='is_email_notify_enabled',
        ),
        migrations.RemoveField(
            model_name='m_userprofile',
            name='is_notify_comment',
        ),
        migrations.RemoveField(
            model_name='m_userprofile',
            name='is_notify_follow',
        ),
        migrations.RemoveField(
            model_name='m_userprofile',
            name='is_notify_like',
        ),
    ]
