"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from datetime import datetime, timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# PROJECT_DIR = os.path.basename(BASE_DIR) # 冗長なため削除

env = environ.Env()
env.read_env(os.path.join(BASE_DIR, ".env"))

# ==============================================================================
# 1. CORE SETTINGS
# ==============================================================================
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
SECRET_KEY: str = env("SECRET_KEY")
DEBUG: bool = env.bool("DEBUG", default=False)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# デバッグログ出力設定
IS_DEBUG_LOG_OUTPUT: bool = env.bool("IS_DEBUG_LOG_OUTPUT", default=False)

# セッション/クッキー設定(HTTPS設定を想定しない場合はFalseのまま)
SESSION_COOKIE_SECURE: bool = env.bool("SESSION_COOKIE_SECURE", default=False)
SESSION_COOKIE_AGE: int = 60
CSRF_COOKIE_SECURE: bool = env.bool("CSRF_COOKIE_SECURE", default=False)
# セキュリティ推奨設定
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
X_FRAME_OPTIONS = "DENY"  # クリックジャッキング対策
TOKEN_EXPIRY_SECONDS = {
    "activation": int(os.environ.get("TOKEN_EXPIRY_ACTIVATION_SECONDS", 86400)),
    "password_reset": int(os.environ.get("TOKEN_EXPIRY_PASSWORD_RESET_SECONDS", 3600)),
    # ... 他のトークン種別も追加 ...
}

# ==============================================================================
# 2. APPLICATION DEFINITION
# ==============================================================================
INSTALLED_APPS = [
    # Django 標準 Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Siteフレームワークの追加
    # 外部パッケージ
    # プロジェクト固有 Apps (新しい構成)
    "core",  # 共通機能
    "account",  # ユーザー認証・プロフィール
    # "product",    # 作品・違反報告
    # "article",    # 記事・チュートリアル
    # "message",    # プライベートメッセージ
    "home",  # ユーザー認証・プロフィール
]
SITE_ID = 1
MIDDLEWARE = [
    # 独自ミドルウェア (SameSiteMiddlewareはCSRF/SessionMiddlewareより前に配置)
    "core.middlewares.same_site_middleware.SameSiteMiddleware",
    # Django 標準 Middleware
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # アクセスログ設定ミドルウェア
    "core.middlewares.logging_middleware.LoggingMiddleware",
]
ROOT_URLCONF = "config.urls"
# 特定のシステムチェック警告を非表示にする
# W004: USERNAME_FIELDがuniqueでないことに対する警告
SILENCED_SYSTEM_CHECKS = [
    "auth.W004",
]

# ==============================================================================
# 3. TEMPLATES
# ==============================================================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # プロジェクトレベルのtemplatesとcore/templatesを登録
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
            # os.path.join(BASE_DIR, "core", "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # 共通データのためのカスタムコンテキストプロセッサがあれば追記
                # 'core.context_processors.global_data',
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ==============================================================================
# 4. DATABASE & AUTHENTICATION
# ==============================================================================
DATABASES = {
    "default": {
        "ENGINE": env("DB_ENGINE"),
        "NAME": BASE_DIR / env("DB_NAME"),
        "ATOMIC_REQUESTS": env.bool("ATOMIC_REQUESTS"),
        "CONN_MAX_AGE": env.int("CONN_MAX_AGE"),
    },
}
# ユーザー認証モデルの設定（ユーザーマスタ）
AUTH_USER_MODEL = "account.M_User"
AUTHENTICATION_BACKENDS = [
    # "django.contrib.auth.backends.ModelBackend",  # Djangoデフォルト/認証バックエンド
    "core.auth_scheme.user_auth_backend.UserAuthBackend",  # カスタム/認証バックエンド(ユーザID(メールアドレス)/パスワード)
]
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ==============================================================================
# 5. INTERNATIONALIZATION & STATIC FILES
# ==============================================================================
# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = "ja"
TIME_ZONE = "Asia/Tokyo"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # デプロイ時に必要

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==============================================================================
# 6. CLOUDINARY & EMAIL
# ==============================================================================
CLOUDINARY_CLOUD_NAME: str = env("CLOUDINARY_CLOUD_NAME", default="")
CLOUDINARY_API_KEY: str = env("CLOUDINARY_API_KEY", default="")
CLOUDINARY_API_SECRET: str = env("CLOUDINARY_API_SECRET", default="")
CLOUDINARY_UPLOAD_BASE_PATH: str = env("CLOUDINARY_UPLOAD_BASE_PATH", default="")

EMAIL_BACKEND = env(
    "EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend"
)
EMAIL_FROM = env("EMAIL_FROM", default="noreply@example.com")

# ==============================================================================
# 7. LOGGING
# ==============================================================================
# ファイル名を読み込み時に固定
DEBUG_SQL_LOG_FILENAME = (
    f"{BASE_DIR}/logs/debug/{datetime.now():%Y%m%d}_sql_debug_access.log"
)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    # フォーマットの設定
    "formatters": {
        # APIアクセスログ
        "access": {
            "format": "[{asctime}] {levelname} {process:d} {thread:d} {message}",
            "style": "{",
        },
        # アプリケーションログ
        "application": {
            "format": "[{asctime}] {levelname} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    # ハンドラ設定
    "handlers": {
        "handler_access": {
            "level": "DEBUG",  # DEBUGレベル以下は出さない(全てのレベルを出力)
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": f"{BASE_DIR}/logs/access/access.log",
            "formatter": "access",
            "encoding": "utf-8",
            "when": "MIDNIGHT",
            "backupCount": env.int("ACCESS_LOG_BACKUP_COUNT"),
        },
        "handler_application": {
            "level": "DEBUG",  # DEBUGレベル以下は出さない(全てのレベルを出力)
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": f"{BASE_DIR}/logs/application/application.log",
            "formatter": "application",
            "encoding": "utf-8",
            "when": "MIDNIGHT",
            "backupCount": env.int("APPLICATION_LOG_BACKUP_COUNT"),
        },
        "handler_debug_db_access": {
            "level": "DEBUG",  # DEBUGレベル以下は出さない(全てのレベルを出力)
            "class": "logging.FileHandler",
            # ファイル名を読み込み時に固定
            "filename": DEBUG_SQL_LOG_FILENAME,
            "formatter": "access",
            "encoding": "utf-8",
        },
    },
    # ロガー設定
    "loggers": {
        "logger_access": {
            "handlers": ["handler_access"],
            "level": "DEBUG",  # DEBUGレベル以下は出さない(全てのレベルを出力)
            "propagate": True,
        },
        "logger_application": {
            "handlers": ["handler_application"],
            "level": "DEBUG",  # DEBUGレベル以下は出さない(全てのレベルを出力)
            "propagate": True,
        },
        "django.db.backends": {
            # DEBUGモードかつIS_DEBUG_LOG_OUTPUTがTrueの場合のみハンドラを設定
            "handlers": (
                ["handler_debug_db_access"] if DEBUG and IS_DEBUG_LOG_OUTPUT else []
            ),
            "level": "DEBUG",  # DEBUGレベル以下は出さない(全てのレベルを出力)
            "propagate": True,
        },
    },
}
